In [18]:
import torch
import numpy as np

In [56]:
# Создайте случайный FloatTensor размера 3x4x5
tensor_1 = torch.randn([3, 4, 5], dtype=torch.float)
tensor_1

tensor([[[ 1.2704,  0.6585,  0.4888,  0.3403,  0.3507],
         [ 0.0646, -1.2628,  0.8486, -0.7812, -0.5085],
         [-1.8098,  0.4867,  0.2217, -0.5615, -0.6773],
         [-2.3121, -1.9064, -1.3019,  0.7841, -0.9451]],

        [[-0.4101, -0.8040, -0.0609, -0.9398,  1.8925],
         [-1.9541, -0.1773,  1.6474,  0.0321, -0.9665],
         [-0.9208,  0.2201, -0.4511,  0.6334,  0.4777],
         [ 0.0681,  0.4563,  0.1469,  1.4286,  0.8917]],

        [[ 0.3066, -0.3253,  0.1033,  0.2859,  1.0316],
         [-0.5530, -2.5768, -0.0754, -1.7780, -0.2304],
         [-0.5671,  0.9737, -1.2449, -1.3834,  1.0132],
         [ 0.8108, -0.7414,  0.9593,  0.4491,  0.3187]]])

In [57]:
# Выведите его форму (shape)
tensor_1.shape

torch.Size([3, 4, 5])

In [58]:
# Приведите его к форме 6 X 10
tensor_2 = tensor_1.view([6, 10])
tensor_2

tensor([[ 1.2704,  0.6585,  0.4888,  0.3403,  0.3507,  0.0646, -1.2628,  0.8486,
         -0.7812, -0.5085],
        [-1.8098,  0.4867,  0.2217, -0.5615, -0.6773, -2.3121, -1.9064, -1.3019,
          0.7841, -0.9451],
        [-0.4101, -0.8040, -0.0609, -0.9398,  1.8925, -1.9541, -0.1773,  1.6474,
          0.0321, -0.9665],
        [-0.9208,  0.2201, -0.4511,  0.6334,  0.4777,  0.0681,  0.4563,  0.1469,
          1.4286,  0.8917],
        [ 0.3066, -0.3253,  0.1033,  0.2859,  1.0316, -0.5530, -2.5768, -0.0754,
         -1.7780, -0.2304],
        [-0.5671,  0.9737, -1.2449, -1.3834,  1.0132,  0.8108, -0.7414,  0.9593,
          0.4491,  0.3187]])

In [59]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
tensor_1 * torch.IntTensor([1, 4, 2, 2, 1])

tensor([[[  1.2704,   2.6339,   0.9777,   0.6806,   0.3507],
         [  0.0646,  -5.0513,   1.6971,  -1.5624,  -0.5085],
         [ -1.8098,   1.9467,   0.4434,  -1.1230,  -0.6773],
         [ -2.3121,  -7.6257,  -2.6038,   1.5682,  -0.9451]],

        [[ -0.4101,  -3.2161,  -0.1218,  -1.8796,   1.8925],
         [ -1.9541,  -0.7093,   3.2947,   0.0641,  -0.9665],
         [ -0.9208,   0.8804,  -0.9021,   1.2668,   0.4777],
         [  0.0681,   1.8251,   0.2937,   2.8571,   0.8917]],

        [[  0.3066,  -1.3012,   0.2066,   0.5717,   1.0316],
         [ -0.5530, -10.3072,  -0.1508,  -3.5561,  -0.2304],
         [ -0.5671,   3.8947,  -2.4897,  -2.7668,   1.0132],
         [  0.8108,  -2.9657,   1.9186,   0.8982,   0.3187]]])

In [60]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.matmul(tensor_2, torch.t(tensor_2))

tensor([[ 5.7131, -1.2777,  1.2257, -2.8789,  5.3454,  0.4865],
        [-1.2777, 16.5187,  3.2331,  0.0532,  3.5634, -0.3444],
        [ 1.2257,  3.2331, 12.7820, -0.2513,  3.3923,  2.5770],
        [-2.8789,  0.0532, -0.2513,  4.7995, -3.6967,  1.6894],
        [ 5.3454,  3.5634,  3.3923, -3.6967, 11.5223,  0.5484],
        [ 0.4865, -0.3444,  2.5770,  1.6894,  0.5484,  8.1906]])

In [61]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable

In [77]:
x = Variable(torch.ones(3), requires_grad=True)
z = Variable(torch.ones(3), requires_grad=True)
t = Variable(torch.ones(3), requires_grad=True)

In [78]:
y = x**3 + z - 75*t
y

tensor([-73., -73., -73.], grad_fn=<SubBackward0>)

In [79]:
y.backward(torch.tensor([1, 0.5, 2]))

In [84]:
print(f'Gradient by X: {x.grad}')
print(f'Gradient by Z: {z.grad}')
print(f'Gradient by T: {t.grad}')

Gradient by X: tensor([3.0000, 1.5000, 6.0000])
Gradient by Z: tensor([1.0000, 0.5000, 2.0000])
Gradient by T: tensor([ -75.0000,  -37.5000, -150.0000])


In [82]:
# Создайте единичный тензор размера 5x6
tensor_3 = torch.ones(5, 6)
tensor_3

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [83]:
# Переведите его в формат numpy
tensor_3.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [205]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch import nn 
from torch import optim

In [264]:
linear = nn.Linear(2, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.1132,  0.2085],
        [ 0.3391, -0.0188]], requires_grad=True)
b:  Parameter containing:
tensor([-0.0369, -0.2505], requires_grad=True)


In [265]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.001)

In [266]:
x = Variable(torch.rand(2), requires_grad = True)
x

tensor([0.7586, 0.3318], requires_grad=True)

In [267]:
y = Variable(x**linear.weight[1] - 2 * x**2 + 5, requires_grad = False)
y

tensor([4.7595, 5.8008])

In [268]:
optimizer.zero_grad()
pred = linear(x)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  27.592998504638672


In [269]:
loss.backward()

In [270]:
print ('dL/dw: ', linear.weight.grad) 
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-3.5212, -1.5400],
        [-4.4003, -1.9245]])
dL/db:  tensor([-4.6414, -5.8003])


In [271]:
optimizer.step()

In [272]:
print ('w: ', linear.weight)
print ('b: ', linear.bias)

w:  Parameter containing:
tensor([[ 0.1167,  0.2100],
        [ 0.3435, -0.0169]], requires_grad=True)
b:  Parameter containing:
tensor([-0.0323, -0.2447], requires_grad=True)


In [273]:
optimizer.zero_grad()
pred = linear(x)
loss = criterion(pred, y)
print('loss: ', loss.item())

loss:  27.500049591064453


In [274]:
for i in range(20):
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    pred = linear(x)
    loss = criterion(pred, y)
    print('loss: ', loss.item())

loss:  27.40742301940918
loss:  27.315101623535156
loss:  27.223094940185547
loss:  27.13139533996582
loss:  27.04000473022461
loss:  26.948925018310547
loss:  26.858150482177734
loss:  26.76767921447754
loss:  26.677513122558594
loss:  26.5876522064209
loss:  26.498096466064453
loss:  26.40884017944336
loss:  26.319883346557617
loss:  26.23122787475586
loss:  26.14286994934082
loss:  26.0548095703125
loss:  25.96704864501953
loss:  25.879579544067383
loss:  25.79240608215332
loss:  25.705528259277344
